site_name: Home Assistant Dokumentaatio
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - toc.integrate
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  - autorefs
  language: fi
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        title: Dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        title: Light mode
      primary: teal
      accent: lime


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/JonneSaloranta

copyright: '&copy 2024 <a href="https://github.com/JonneSaloranta" target="_blank" rel="noopener">Jonne Saloranta</a>'